[build]
  command = "npm run build" # Or "yarn build", "vite build", etc.
  publish = "build" # Or "dist", "out", etc.

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript" # Or "text/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"